from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, is_dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal, NotRequired, TypedDict
from uuid import UUID


class ResearchPhase(str, Enum):
    """Deep Research phase state machine."""

    INIT = "init"
    PLANNING = "planning"
    RESEARCHING = "researching"
    ANALYZING = "analyzing"
    WRITING = "writing"
    REVIEWING = "reviewing"
    RE_RESEARCHING = "re_researching"
    REVISING = "revising"
    COMPLETED = "completed"


CheckpointStatus = Literal["running", "paused", "completed", "failed", "cancelled"]
SectionStatus = Literal["pending", "researching", "drafted", "reviewed", "final"]
SectionType = Literal["qualitative", "quantitative", "mixed"]
SourceType = Literal["local", "web", "official", "academic", "news", "report", "self_media"]
ChartType = Literal["line", "bar", "pie", "scatter", "table", "heatmap"]
IssueType = Literal[
    "missing_source",
    "logic_error",
    "bias",
    "hallucination",
    "outdated",
    "incomplete",
]
IssueSeverity = Literal["critical", "major", "minor"]


def utc_now() -> datetime:
    """Return timezone-aware UTC timestamps for serializable state entries."""
    return datetime.now(timezone.utc)


@dataclass(slots=True)
class Section:
    """One report section planned or produced by Deep Research agents."""

    id: str
    title: str
    description: str
    section_type: SectionType = "mixed"
    status: SectionStatus = "pending"
    content: str = ""
    sources: list[str] = field(default_factory=list)
    subsections: list["Section"] = field(default_factory=list)
    requires_data: bool = False
    requires_chart: bool = False


@dataclass(slots=True)
class Fact:
    """A structured fact collected by web or local retrieval agents."""

    id: str
    content: str
    source_url: str = ""
    source_name: str = ""
    source_type: SourceType = "web"
    credibility_score: float = 0.0
    extracted_at: datetime = field(default_factory=utc_now)
    related_sections: list[str] = field(default_factory=list)
    verified: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class DataPoint:
    """A normalized numeric or categorical value extracted during research."""

    id: str
    name: str
    value: Any
    unit: str = ""
    year: int | None = None
    source: str = ""
    confidence: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Chart:
    """Chart payload generated by analysis agents."""

    id: str
    title: str
    chart_type: ChartType
    data: dict[str, Any]
    code: str = ""
    image_path: str | None = None
    section_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class CriticFeedback:
    """Review feedback produced by critic agents."""

    id: str
    target_section: str
    issue_type: IssueType
    severity: IssueSeverity
    description: str
    suggestion: str
    resolved: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AgentLog:
    """Execution log entry for one agent action."""

    timestamp: datetime
    agent: str
    action: str
    input_summary: str = ""
    output_summary: str = ""
    duration_ms: int = 0
    tokens_used: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AgentEvent:
    """Streamable multi-agent execution event, not an ordinary chat message."""

    type: str
    agent: str
    content: Any
    timestamp: datetime = field(default_factory=utc_now)
    phase: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class PhaseOutput:
    """Persisted result summary after one Deep Research phase completes."""

    phase: str
    status: CheckpointStatus
    output: dict[str, Any] = field(default_factory=dict)
    completed_at: datetime = field(default_factory=utc_now)
    agent: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AgentOutput:
    """Persisted result summary after one agent finishes work."""

    agent: str
    phase: str
    status: CheckpointStatus
    output: dict[str, Any] = field(default_factory=dict)
    completed_at: datetime = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)


class ResearchState(TypedDict):
    """Global working memory shared by Deep Research agents."""

    query: str
    user_id: str | None
    session_id: str
    phase: str
    iteration: int
    max_iterations: int
    search_web: bool
    search_local: bool
    outline: list[dict[str, Any]]
    mind_map: dict[str, Any]
    key_entities: list[str]
    research_questions: list[str]
    hypotheses: list[dict[str, Any]]
    knowledge_graph: dict[str, Any]
    facts: list[dict[str, Any]]
    data_points: list[dict[str, Any]]
    raw_sources: list[dict[str, Any]]
    charts: list[dict[str, Any]]
    code_executions: list[dict[str, Any]]
    insights: list[str]
    draft_sections: dict[str, str]
    final_report: str
    references: list[dict[str, Any]]
    critic_feedback: list[dict[str, Any]]
    unresolved_issues: int
    quality_score: float
    review_verdict: str
    forced_completed: bool
    pending_search_queries: list[str]
    phase_outputs: list[dict[str, Any]]
    agent_outputs: list[dict[str, Any]]
    agent_events: list[dict[str, Any]]
    logs: list[dict[str, Any]]
    errors: list[str]
    runtime: NotRequired[dict[str, Any]]


RUNTIME_STATE_KEYS = {
    "_message_queue",
    "_user_id",
    "messages",
    "runtime",
    "llm_client",
    "openai_client",
    "milvus_client",
    "redis_client",
    "db",
    "session",
    "task",
    "tasks",
}


def create_initial_state(
    query: str,
    session_id: UUID | str,
    user_id: UUID | str | None = None,
    search_web: bool = True,
    search_local: bool = False,
    max_iterations: int = 3,
) -> ResearchState:
    """Create the initial Deep Research state for a multi-agent run."""

    return ResearchState(
        query=query,
        user_id=str(user_id) if user_id is not None else None,
        session_id=str(session_id),
        phase=ResearchPhase.INIT.value,
        iteration=0,
        max_iterations=max_iterations,
        search_web=search_web,
        search_local=search_local,
        outline=[],
        mind_map={},
        key_entities=[],
        research_questions=[],
        hypotheses=[],
        knowledge_graph={"nodes": [], "edges": []},
        facts=[],
        data_points=[],
        raw_sources=[],
        charts=[],
        code_executions=[],
        insights=[],
        draft_sections={},
        final_report="",
        references=[],
        critic_feedback=[],
        unresolved_issues=0,
        quality_score=0.0,
        review_verdict="",
        forced_completed=False,
        pending_search_queries=[],
        phase_outputs=[],
        agent_outputs=[],
        agent_events=[],
        logs=[],
        errors=[],
    )


def to_serializable(value: Any) -> Any:
    """Convert common state objects into JSON-compatible values."""

    if is_dataclass(value):
        return to_serializable(asdict(value))
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, dict):
        return {str(key): to_serializable(item) for key, item in value.items()}
    if isinstance(value, list | tuple | set):
        return [to_serializable(item) for item in value]

    try:
        json.dumps(value)
    except (TypeError, ValueError):
        return str(value)
    return value


def clean_state_for_checkpoint(state: dict[str, Any]) -> dict[str, Any]:
    """Remove runtime-only objects before storing Deep Research state."""

    clean: dict[str, Any] = {}
    for key, value in state.items():
        if key in RUNTIME_STATE_KEYS or key.startswith("_"):
            continue
        clean[key] = to_serializable(value)
    return clean


def section_to_dict(section: Section) -> dict[str, Any]:
    return to_serializable(section)


def fact_to_dict(fact: Fact) -> dict[str, Any]:
    return to_serializable(fact)


def data_point_to_dict(data_point: DataPoint) -> dict[str, Any]:
    return to_serializable(data_point)


def chart_to_dict(chart: Chart) -> dict[str, Any]:
    return to_serializable(chart)


def critic_feedback_to_dict(feedback: CriticFeedback) -> dict[str, Any]:
    return to_serializable(feedback)


def agent_log_to_dict(log: AgentLog) -> dict[str, Any]:
    return to_serializable(log)


def agent_event_to_dict(event: AgentEvent) -> dict[str, Any]:
    return to_serializable(event)


def phase_output_to_dict(output: PhaseOutput) -> dict[str, Any]:
    return to_serializable(output)


def agent_output_to_dict(output: AgentOutput) -> dict[str, Any]:
    return to_serializable(output)
